---
name: README.md
on:
  push:
    paths:
    - '.github/workflows/*'
    - 'templates/*'
    - 'docs/*'
  workflow_dispatch:
  repository_dispatch:
    types: [update-readme]

permissions:
  id-token: write
  contents: write

jobs:
  generate-readme:
    uses: jmpa-io/roots/.github/workflows/README.yml@main
    secrets: inherit

  post-to-slack:
    needs: [generate-readme]
    if: always()
    uses: jmpa-io/roots/.github/workflows/post-to-slack.yml@main
    secrets: inherit
